### ISSUE TITLE
All prices for listings on Blockmarket display as "$0",  or "0 SYS" .   Also problem with balance information sometimes displaying as 0 instead of what is actually in there.  Also problem with information in the Offers and Certificates windows showing up as code instead of the correct number "0".

### ISSUE THREAD

**Issue by 3-dollar-syscoin** [syscoin/blockmarket-desktop-public#236]
Re-downloaded and re-installed blockmarket Ver. 1,  this did not solve it.  

Also,  sometimes my balance will display as zero in the balance window of the main page,  until I flip back and forth between my "alias" and "all accounts".  Then it will be OK,  but sometimes it will go back to being incorrect.

Also,  sometimes code will show up instead of "0" in the Offers and Certificates windows.  It will display as " [object Object]  " instead.  If I go to a different screen  and go back or switch from all accounts to my alias,    it will be OK, but then that will sometimes go back to displaying incorrectly if I change or move between screens again.

**Comment by sidhujag** [comment]
Both of these fixed in next release 1.0.2

**Comment by 3-dollar-syscoin** [comment]
How do you know that?

**Comment by sidhujag** [comment]
Download 1.0.1 the 0 count issue is fixed. The balance issue will be tomorrow in 1.0.2

**Comment by 3-dollar-syscoin** [comment]
I should have added originally that I am running Win 8.1.  Should these updates still fix the issues that I am having with not being able to see anything other than "$0" or "0 SYS" for the prices of all listings on the Blockmarket even though I am not on a Mac?  I heard that the 1.0.1 is mostly for Mac issues so I didn't try it yet.

**Comment by sidhujag** [comment]
Yes

**Comment by 3-dollar-syscoin** [comment]
OK,   the " [Object,object ] " problem seems to have gone away by updating to 1.0.1.  But,  do you have an idea as to when 1.0.2 is going to be available?  I still have the issues with the balance not showing up initially,  and I still can't see prices,  just "$0" or "0 SYS" for items listed on the BM.

**Comment by sidhujag** [comment]
Very very soon. Please check back in a day or 2

**Comment by 3-dollar-syscoin** [comment]
Any info?  I still have the problem,  wondering if it is a problem with my system or what is going on.

**Comment by sidhujag** [comment]
Dan is still working on 1.1.. please check back when 1.1 is released eta next week now

**Comment by 3-dollar-syscoin** [comment]
Hate to say it,  but I've loaded Desktop 1.1 and I'm still having issues with SYS balance not initially displaying,  and prices always showing up as "0" on the Blockmarket.

**Comment by sidhujag** [comment]
screenshot?

**Comment by 3-dollar-syscoin** [comment]
![screenshot 6](https://user-images.githubusercontent.com/31973527/32479545-48eee6be-c358-11e7-9a41-46f0730bfcac.png)
![screenshot 7](https://user-images.githubusercontent.com/31973527/32479546-48fb71cc-c358-11e7-8f79-4a87568ea309.png)
![screenshot 8](https://user-images.githubusercontent.com/31973527/32479547-49690782-c358-11e7-84fc-31e71db11ac0.png)
![screenshot 9](https://user-images.githubusercontent.com/31973527/32479548-4983a088-c358-11e7-8da2-1cb9f85f33a0.png)

**Comment by 3-dollar-syscoin** [comment]
Any ideas?  Is this something on my end?

**Comment by dwasyluk** [comment]
@3-dollar-syscoin are you part of our slack? Can you please join and msg us there so we can discuss this in more depth? I'm @danosphere on there.

**Comment by 3-dollar-syscoin** [comment]
I will contact you there.

**Comment by 3-dollar-syscoin** [comment]
Just to update,  all prices still always display as "0" even after updating to BM Desktop 2.0.    I can see prices on my laptop but I could not transfer my alias over, lol.  No worries,  I gave up.  Dano,  I see your PM on Slack but it wants me to pay to read it.
