### ISSUE TITLE
BM hangs on loading screen with error

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#24]
This is the internal issue known as "socket hangup error" it seems to only impact Mac users, and only a subset of mac users. If you hit the error you will get the below message. Please provide as much info on you machine as possible. I ran into it on OSX 10.10.5.

![screen shot 2017-05-09 at 9 41 45 pm](https://cloud.githubusercontent.com/assets/987186/25879607/95f3fd5a-3500-11e7-9cd9-e9ec77fd57c0.png)

**Comment by dwasyluk** [comment]
Thanks to the changes just before release of beta1 api-server 1.0.2 returns the error the client "socket hang up" so the code that pops the error message needs to be updated in order for users to see it, otherwise they just get "loading forever" experience. We should fix the messaging for beta2, this issue shouldn't be closed until the root socket hang up issue is sorted out.

**Comment by willyko** [comment]
10.12.4 hitting the same issue.  syscoind shuts down in the background.

**Comment by malfooh** [comment]
It didn't work also with Windows 7 32bit, it only stucks at loading for ever, when i close BM,  its process still hangs in task manager

**Comment by VictorAtila** [comment]
Same problem as Malfooh, Window 32bit, it gets stuck in loading for ever without an error.

**Comment by dwasyluk** [comment]
We have a fix for this on Mac, it would not fix the windows issue though. Once we confirm the mac fix with a larger user base we'll close this issue and create a related, win32-only version of the bug as it seems to have a possibly different root cause on win32.

**Comment by sebastien1234** [comment]
I was getting this issue on a fairly rare and intermittent basis, would just hand on that screen and keep rolling forever. A restart of the wallet fixed it every time. Since Beta 2 I haven't experienced the hanging at all as-of-yet. Will comment again if I do. Window 10 64bit

**Comment by dwasyluk** [comment]
Closing this as it related to MacOSX. Please create a new bug specific to windows if something is still not working on win32, thanks!
